### ISSUE TITLE
? insert-string is void?

### ISSUE THREAD

**Issue by DJJ88** [dtaht/Gnugol#8]
Hello,

I've tried gnugol but I got the error that the function insert-string is void.
I've have the issue by using (insert .... ) instead of (insert-string ... )
in the gnugol.el file. 
Is the insert-string function doing something better ?

**Comment by dtaht** [comment]
Hey, thx for trying gnugol. I've not got around to making the gnugol.el file do much useful, sorry. My emacs-fu is lacking.

**Comment by rafiks** [comment]
when i watched Jay Dixit's video, this was working. was there a change to the code that broked this or did @jaydixit fixed it himself? I might need to email him. :)

**Comment by rafiks** [comment]
I found the solution in one of the spacemacs tickets.
apparently, Emacs version >24 lacks the insert-string function.
`(defalias 'insert-string 'insert)`
https://github.com/syl20bnr/spacemacs/issues/7790

**Comment by DJJ88** [comment]
Hello I apologize for the delayed reply. Many thanks for your answer.  
I confess that I had given up on gnugol. I'm going to close the post.
It seem that is not maintained anymore on melpa.  Are you still using it?
